#!/usr/bin/ruby
require 'uri'
site = (URI).parse(ENV['DWB_URI']).host

password = `zenity --password`
hashedPassword = `~/bin/pwdhash.js #{site} #{password}`.chomp!

IO.binwrite(ENV['DWB_FIFO'], "open javascript:document.activeElement.value='#{hashedPassword}'")
